import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";

import { login, logout, selectUser } from "../features/userSlice";
import { auth } from "../firebase";
import requests from "../requests";
import LoginScreen from "../screens/LoginScreen";

export default function Home({ results }) {
  
  const user = useSelector(selectUser);
  const dispatch = useDispatch();
  useEffect(() => {
    const unSubscribe = auth.onAuthStateChanged((userAuth) => {
      if (userAuth) {
        dispatch(
          login({
            uid: userAuth.uid,
            email: userAuth.email,
          })
        );
      } else {
        dispatch(logout);
      }
    });
    return unSubscribe;
  }, []);

  return (
    <div className="">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://findicons.com/files/icons/1253/flurry_extras/256/hulu.png"
        />
      </Head>

      {!user ? (
        <LoginScreen />
      ) : (
        <div className="text-gray-300">
          <Header />
          <Nav />
          <Result results={results}/>
        
        </div>
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    ` https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchHuluOriginals.url
    }`
  ).then((res)=>res.json())
  

  return {
    props: {
      results:request.results
    }, // will be passed to the page component as props
  };
}
